Feat/execute timeout
WasmEdge/wasmedge-rust-sdk pull request #61
Opened 2023-09-06 16:07 UTC by L-jasmine

2023-09-06 16:07 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-09-06 22:17 UTC, apepkuss commented
@L-jasmine Please fix the clippy issues on `MacOS` and `Windows` to guarantee all CI workflows pass. Thanks!

2023-09-07 10:40 UTC, apepkuss commented on src/externals/function.rs
> +    pub fn run_timeout(
Rename `run_timeout` to `run_with_timeout`. Thanks!

2023-09-07 10:40 UTC, apepkuss commented on src/externals/function.rs
> +    pub async fn run_async_timeout(
Rename `run_async_timeout` to `run_async_with_timeout`. Thanks!

2023-09-07 11:35 UTC, apepkuss requested changes

2023-09-07 11:35 UTC, apepkuss commented on src/executor.rs
> +    /// Asynchronously runs a host function instance and returns the results.
Refine the comments: `Asynchronously runs a host function instance with a timeout setting.`

Thanks!

2023-09-07 11:35 UTC, apepkuss commented on src/externals/function.rs
> +    /// Runs this host function and returns the result.
Refine the comments: `Runs this host function with a timeout setting.`

2023-09-07 11:35 UTC, apepkuss commented on src/vm.rs
> +    /// Runs an exported wasm function in a (named or active) [module instance](crate::Instance).
Refine the comments: `Runs an exported wasm function in a (named or active) [module instance](crate::Instance) with a timeout setting.`

Thanks!

2023-09-07 11:35 UTC, apepkuss commented on src/vm.rs
> +    /// Asynchronously runs an exported wasm function in a (named or active) [module instance](crate::Instance).
Refine the comments: `Asynchronously runs an exported wasm function in a (named or active) [module instance](crate::Instance) with a timeout setting.`

Thanks!

2023-09-07 11:35 UTC, apepkuss commented on src/executor.rs
> +    /// * `timeout_sec` - The maximum execution time in seconds for the function instance.
1. Rename timeout_sec to timeout.
2. Refine the comments: The maximum execution time (in seconds) of the function to be run.

Thanks!

2023-09-08 04:02 UTC, apepkuss requested changes

2023-09-08 04:03 UTC, apepkuss commented
@L-jasmine Is it possible to add some unit tests for the new APIs? Thanks!

2023-09-09 16:48 UTC, apepkuss approved these changes

2023-09-09 16:49 UTC, merged