[Feat] run func timeout use std::time::Duration
WasmEdge/wasmedge-rust-sdk pull request #76
Opened 2023-09-27 11:04 UTC by L-jasmine

2023-09-27 11:05 UTC, juntao commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-09-28 03:30 UTC, apepkuss requested changes

2023-09-28 03:30 UTC, apepkuss commented on crates/wasmedge-sys/src/executor.rs
> +            value.it_value.tv_nsec = timeout.subsec_nanos() as _;
For better readability, please specify the concrete type used by `as` operator. Thanks a lot!

2023-09-28 03:30 UTC, apepkuss commented on crates/wasmedge-sys/src/async/fiber.rs
> +    /// * `deadline` - The deadline the function instance.
Please refine the description for the `deadline` argument. Thanks a lot!

2023-09-28 03:30 UTC, apepkuss commented on crates/wasmedge-sys/src/async/fiber.rs
> +                let timeout = timeout.unwrap().max(std::time::Duration::from_millis(100));
Please refer to the following code to refine the code snippet for avoiding `unwrap`. Thanks!

```rust
let timeout = match self.deadline.duration_since(std::time::SystemTime::now()) {
    Ok(timeout) => timeout.max( ... ),
    Err(_) => return Poll::Ready(Err(()))
}
```

2023-09-28 03:30 UTC, apepkuss commented on crates/wasmedge-sys/src/async/fiber.rs
>          async_state: &AsyncState,
Please add the description for the `async_state` argument.

2023-10-02 03:18 UTC, apepkuss approved these changes

2023-10-02 03:22 UTC, merged