[CI] Update `rust-static-lib` workflow
WasmEdge/wasmedge-rust-sdk pull request #96
Opened 2023-11-15 14:03 UTC by apepkuss

In this PR, the `rust-static-lib` workflow is updated to match the latest codebase.

2023-11-15 14:04 UTC, apepkuss commented
@hydai Please help review this PR. Thanks a lot!

2023-11-15 17:14 UTC, hydai requested changes

2023-11-15 17:14 UTC, hydai commented on .github/workflows/rust-static-lib.yml
>            apt install -y software-properties-common libboost-all-dev llvm-15-dev liblld-15-dev ninja-build
`libboost-all-dev` is no longer needed.

2023-11-16 01:32 UTC, apepkuss commented on .github/workflows/rust-static-lib.yml
>            apt install -y software-properties-common libboost-all-dev llvm-15-dev liblld-15-dev ninja-build
Accepted. Will remove it, thanks!

2023-11-16 02:02 UTC, apepkuss commented
@hydai The review issue has been fixed. Please help review the updated. Thanks!

2023-11-16 02:37 UTC, hydai approved these changes

2023-11-16 08:23 UTC, apepkuss commented
@hydai Thanks for the review!

2023-11-16 08:23 UTC, merged